# Generated by Django 3.2.9 on 2021-12-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='community_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_bar', models.CharField(max_length=20)),
                ('sec_bar', models.TextField(max_length=20)),
            ],
        ),
    ]
